import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>University Broadcasting App</title>
         <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={styles.cont}>
      </div>
      <main className={styles.main}>
        <h1 className={styles.title}>
          University Broadcasting App
        </h1>
        <div className={styles.auth}>
          <button type="button" className={`${styles.bgPri} btn signup`} onClick={()=> window.location.href= "/auth/signup"}>SignUp</button>
          <button type="button" className={`${styles.bgPri} btn login`} onClick={()=> window.location.href= "/auth/login"}>Login</button>
        </div>
      </main>

      {/* <footer className={styles.footer}>
      </footer> */}
    </div>
  )
}

export default Home
